// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxSj70tg1C63uuDHFhhCAldND_dLdp2GE',
    appId: '1:473180039129:web:0f190c4e887b402686dbc8',
    messagingSenderId: '473180039129',
    projectId: 'chat-b6863',
    authDomain: 'chat-b6863.firebaseapp.com',
    storageBucket: 'chat-b6863.appspot.com',
    measurementId: 'G-MTGFCBNR4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjv-Fz2548c8OqILNqEiYlY1hIvy308NQ',
    appId: '1:473180039129:android:46651ea3cc431f1b86dbc8',
    messagingSenderId: '473180039129',
    projectId: 'chat-b6863',
    storageBucket: 'chat-b6863.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-3D5CpUbybDn7y0gMXGlTKPFauuMpCGE',
    appId: '1:473180039129:ios:f6993a4852ea654a86dbc8',
    messagingSenderId: '473180039129',
    projectId: 'chat-b6863',
    storageBucket: 'chat-b6863.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-3D5CpUbybDn7y0gMXGlTKPFauuMpCGE',
    appId: '1:473180039129:ios:f6993a4852ea654a86dbc8',
    messagingSenderId: '473180039129',
    projectId: 'chat-b6863',
    storageBucket: 'chat-b6863.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxSj70tg1C63uuDHFhhCAldND_dLdp2GE',
    appId: '1:473180039129:web:8072be4e49ec879286dbc8',
    messagingSenderId: '473180039129',
    projectId: 'chat-b6863',
    authDomain: 'chat-b6863.firebaseapp.com',
    storageBucket: 'chat-b6863.appspot.com',
    measurementId: 'G-D4FXV8SPPG',
  );
}
